url: "https://trutz.online"
baseurl: ""
title: "trutz.online"
exclude: ["package.json", "package-lock.json", "tailwind.config.js", "tailwind-input.css", "*.ps1", "renovate.json", "README.md", "compose.yaml"]
plugins:
  - jekyll-include-cache
  - jekyll-sitemap # generiert die sitemap.xml für Google