remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
include: ["_pages"]
title: "trutz.online"
subtitle: "Politischer Foto- und Videojournalismus"
locale: de
date_format: "%-d.%-m.%Y"
url: "https://trutz.online"
author:
  name     : "Christian Trutz"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Politik & Social Media"
  links:
    - label : "YouTube"
      icon  : "fab fa-fw fa-youtube"
      url   : "https://www.youtube.com/c/christiantrutz"
    - label : "Twitter"
      icon  : "fab fa-fw fa-twitter-square"
      url   : "https://twitter.com/christiantrutz"
    - label : "Mastodon"
      icon  : "fab fa-fw fa-mastodon"
      url   : "https://nrw.social/@hadesnews"
    - label : "Instagram"
      icon  : "fab fa-fw fa-instagram"
      url   : "https://www.instagram.com/trutz.online/"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time : true
      share     : true
      layout    : single
analytics:
  provider: "google"
  google:
    tracking_id: "UA-249921293-1"
    anonymize_ip: false # default
plugins:
  - jekyll-include-cache
  - jekyll-sitemap # generiert die sitemap.xml für Google
