remote_theme: "mmistakes/minimal-mistakes@4.22.0"
include: ["_pages"]
minimal_mistakes_skin: "contrast"
locale: de
date_format: "%-d.%-m.%Y"
plugins:
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-feed
  - jekyll-include-cache

